# Sentiment Analysis Configuration
sentiment:
  # Model Configuration
  model: "llama2"              # Primary LLM model
  fallback_model: "roberta"    # Fallback model
  batch_size: 32               # Batch size for processing
  max_length: 512              # Maximum text length
  
  # Thresholds
  threshold: 0.7               # Minimum sentiment score for signal
  volatility_window: 3         # Days for sentiment volatility
  min_sources: 3               # Minimum sources for signal validation
  
  # Source Reliability Weights
  source_weights:
    reuters: 0.95              # High reliability
    bloomberg: 0.90
    cnbc: 0.85
    bbc: 0.90
    al_jazeera: 0.80
    fox: 0.75
    ap: 0.85
    default: 0.50              # Default for unknown sources
  
  # Bias Mitigation
  bias_detection: true         # Enable bias detection
  multi_source_validation: true # Require multiple sources
  political_neutrality: true   # Filter politically biased content

# LLM Configuration
llm:
  # OpenAI (if using)
  openai:
    model: "gpt-4"
    temperature: 0.1
    max_tokens: 1000
  
  # Anthropic (if using)
  anthropic:
    model: "claude-3-sonnet"
    temperature: 0.1
    max_tokens: 1000
  
  # Ollama (local)
  ollama:
    model: "llama2"
    temperature: 0.1
    max_tokens: 1000

# Prompt Templates
prompts:
  sentiment_analysis: |
    Analyze the sentiment of the following news headline regarding oil prices and energy stocks (XOP ETF):
    
    Headline: {headline}
    Source: {source}
    Date: {date}
    
    Please provide:
    1. Sentiment score (-1 to +1, where -1 is very bearish, +1 is very bullish)
    2. Confidence level (0 to 1)
    3. Reasoning for your assessment
    4. Whether this news is likely to impact oil prices significantly
    
    Focus on:
    - Geopolitical implications for oil supply
    - Market sentiment and fear/greed dynamics
    - Historical context of similar events
    - Potential for overreaction vs. genuine impact
    
  novelty_detection: |
    Compare this news event with historical patterns:
    
    Current Event: {current_event}
    Historical Context: {historical_context}
    
    Assess:
    1. Novelty score (0 to 1, where 1 is completely novel)
    2. Similar historical events
    3. Expected market impact based on history
    4. Risk of overreaction

# Clustering Configuration
clustering:
  min_cluster_size: 2          # Minimum articles per cluster
  similarity_threshold: 0.7    # Similarity threshold for clustering
  max_cluster_age: 24          # Hours for cluster validity 